### ISSUE TITLE
TypeError issue with bnlearn.structure_learning.fit()

### ISSUE THREAD

**Issue by magnawhale** [erdogant/bnlearn#19]
I recently installed the **bnlearn** package and had hoped to use it to decipher the network structure of an existing dataset. However, every time I attempt `structure_learning.fit()` I get an error about the datatype.
I used the basic example provided in the installation instructions for the package ([found here](https://erdogant.github.io/bnlearn/pages/html/Installation.html#validate)).
**Inputs**:
```
df = bnlearn.import_example()     
model = bnlearn.structure_learning.fit(df)
```
**Output**:
```
[bnlearn] >Computing best DAG using [hc]
[bnlearn] >Set scoring type at [bic]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/bnlearn/structure_learning.py", line 202, in fit
    adjmat = _dag2adjmat(out['model'])
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/bnlearn/bnlearn.py", line 267, in _dag2adjmat
    adjmat = pd.DataFrame(data=False, index=model.nodes(), columns=model.nodes()).astype('Bool')
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/pandas/core/generic.py", line 5874, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 631, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 626, in astype
    dtype = pandas_dtype(dtype)
  File "/opt/anaconda3/envs/BNLEARN/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1799, in pandas_dtype
    npdtype = np.dtype(dtype)
TypeError: data type 'Bool' not understood
```

I assume the issue is that `'Bool'` should actually be `'bool'` (lowercase) on line 267 of bnlearn.py, but I do not know how to go about fixing this (correcting this in the file on my machine accomplished nothing).
Any thoughts?

**Comment by erdogant** [comment]
Yes it should be 'bool' and not 'Bool'. I fixed this issue before. Can you check the version you are using?

```
import bnlearn as bn
print(bn.__version__)

```

If this is < 0.3.15 then update to the latest version with:

`pip install -U bnlearn
`

**Comment by magnawhale** [comment]
turns out it was a version issue. thanks for the help!
